[package]
name = "collectd_serde"
version = "0.2.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[dependencies]
failure = "0.1.1"
serde = "1.0"

[dependencies.collectd-plugin]
path = ".."
version = "0.2"

[dev-dependencies]
serde_derive = "1.0"
