sudo: required

services:
- docker

language: rust

matrix:
  fast_finish: true
  include:
    - rust: 1.24.1
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: stable
      env: UBUNTU_VERSION=14.04 COLLECTD_VERSION=5.4
    - rust: stable
      env: UBUNTU_VERSION=16.04 COLLECTD_VERSION=5.5
    - rust: stable
      env: UBUNTU_VERSION=18.04 COLLECTD_VERSION=5.7

script:
  - COLLECTD_VERSION=5.5 cargo build --all --features "serde"
  - COLLECTD_VERSION=5.5 cargo test --all --features "serde"
  - if [ ! -z $UBUNTU_VERSION ]; then docker build -t collectd-rust-plugin --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} --build-arg COLLECTD_VERSION=${COLLECTD_VERSION} .; fi;
  - if [ ! -z $UBUNTU_VERSION ]; then docker run -ti collectd-rust-plugin bash -c "COLLECTD_VERSION=${collectd} (cd /tmp && exec ci/test.sh)"; fi;
