language: rust
sudo: required
rust:
  - stable
  - beta
  - nightly
before_install:
  - 'sudo apt install -y --no-install-recommends collectd collectd-dev curl build-essential'
  - 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -'
  - 'sudo apt-get install llvm-3.9-dev libclang-3.9-dev clang-3.9'
  - 'sudo cp -r /usr/include/collectd/liboconfig /usr/include/collectd/core/.'

install:
  ci/test.sh
