language: rust
rust:
  - 1.23.0
  - stable
  - beta
  - nightly

env:
  - COLLECTD_VERSION=5.4 FEATURES=""
  - COLLECTD_VERSION=5.5 FEATURES=""
  - COLLECTD_VERSION=5.7 FEATURES=""
  - COLLECTD_VERSION=5.4 FEATURES="serde"
  - COLLECTD_VERSION=5.5 FEATURES="serde"
  - COLLECTD_VERSION=5.7 FEATURES="serde"
script:
  - cargo build --all --features "$FEATURES"
  - cargo test --all --features "$FEATURES"
