os: Visual Studio 2015

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

# Due to unresolved symbols that the plugin needs to reference from collectd
# we can only build the core module. Collectd doesn't work on windows so this
# isn't something we really should care about
test_script:
  - set COLLECTD_VERSION=5.5
  - cargo build --features serde
