[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "collectd-rust-plugin"
version = "0.1.0"

[build-dependencies]
bindgen = { version = "0.31.3", optional = true }

[dependencies]
chrono = "0.4.0"
failure = "0.1.0"
failure_derive = "0.1.0"

[features]
collectd-54 = []
collectd-55 = []
collectd-57 = []
default = []

[lib]
crate-type = ["dylib"]
name = "myplugin"
