[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "collectd-rust-plugin"
version = "0.1.0"

[build-dependencies]
bindgen = "0.30"

[dependencies]
error-chain = "0.11.0"

[lib]
crate-type = ["dylib"]
name = "myplugin"
