[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "collectd-plugin"
version = "0.4.1"
description = "Provides ergonomic API ontop of collectd's C interface and macro for defining plugins easier"
repository = "https://github.com/nickbabcock/collectd-rust-plugin"
readme = "README.md"
keywords = ["collectd", "plugin"]
categories = ["external-ffi-bindings"]
license = "MIT"

[build-dependencies]
bindgen = { version = "0.32.1", optional = true }

[dependencies]
chrono = "0.4.0"
failure = "0.1.1"
bitflags = "1.0"
serde = { version = "1", optional = true }

[dev-dependencies]
serde_derive = "1.0"
criterion = "0.2"

[features]
collectd-54 = []
collectd-55 = []
collectd-57 = []
stub = []
default = []

[workspace]
members = ['plugins/load', 'plugins/readme', 'plugins/write_log', 'plugins/write_graphite']

[[bench]]
name = "collectd_bench"
harness = false
