[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "collectd-rust-plugin"
version = "0.1.0"

[build-dependencies]
bindgen = "0.31.3"

[dependencies]
chrono = "0.4.0"
error-chain = "0.11.0"

[features]
collectd-57 = []
default = []

[lib]
crate-type = ["dylib"]
name = "myplugin"
