tag-prefix = "v"
tag-message = "Release {{version}}"
dev-version-ext = "pre"
push-remote = false
pre-release-commit-message = "Release {{version}}"
pre-release-replacements = [ {file="CHANGELOG.md", search="Unreleased - TBA", replace="{{version}} - {{date}}"}, {file="README.md", search="= \"\d+\.\d+\.\d+\"", replace="= \"{{version}}\"", {file="src/lib.rs", search="= \"\d+\.\d+\.\d+\"", replace="= \"{{version}}\""]
pro-release-commit-message = "Bump to {{version}}"
