[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "readme-example"
version = "0.2.0"
publish = false

[dependencies]
failure = "0.1.1"

[dependencies.collectd-plugin]
path = ".."
version = "0.2"

[lib]
crate-type = ["cdylib"]
name = "readmeplugin"
