[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "readme-example"
version = "0.2.0"

[dependencies]
failure = "0.1.0"
lazy_static = "0.2.11"

[dependencies.collectd-plugin]
path = ".."
version = "0.2"

[lib]
crate-type = ["dylib"]
name = "readmeplugin"
